# Generated by Django 4.2 on 2023-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_sorting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='contents',
            field=models.ManyToManyField(blank=True, to='trash_sorting.content'),
        ),
    ]
