# Generated by Django 4.2 on 2023-05-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trash_sorting', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortsystem',
            name='location',
        ),
        migrations.AddField(
            model_name='address',
            name='parent_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trash_sorting.sortsystem'),
        ),
        migrations.AddField(
            model_name='sortsystem',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
