# Generated by Django 4.2 on 2023-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_sorting', '0004_remove_sortsystem_location_address_parent_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
